### ISSUE TITLE
Datafy / Nav support

### ISSUE THREAD

**Issue by glittershark** [into-docker/clj-docker-client#2]
A little open-ended, but I was thinking it'd be cool to support the new datafy and nav in this lib - `(datafy conn)` could eg return `(docker/info conn)`, and `nav` could navigate from containers to images etc.

**Comment by lispyclouds** [comment]
datafy/nav are super cool features in 1.10 but unfortunately I'm yet to read about them properly. Will explore and work on it. Navigating docker outputs are definitely useful and any PRs are most welcome!

**Comment by glittershark** [comment]
In case I do get around to throwing up some patches for this, do you have interest in maintaining backwards compatibility with old versions of Clojure?

**Comment by lispyclouds** [comment]
I guess it should be okay till the 1.0 milestone and the fact that its already using Clojure 1.10. So backwards compat isn't a big priority as of now.

**Comment by lispyclouds** [comment]
Closing this for now as there doesn't seem to be a pressing need as we are quite data driven already. Reopen if needed!
