### ISSUE TITLE
Support for other protocols

### ISSUE THREAD

**Issue by mikroskeem** [into-docker/clj-docker-client#27]
... besides `unix` of course.

**Comment by mikroskeem** [comment]
Or not... lol. Seems like raw unix socket is exposed over API and not sure what to do when TCP must be used.

Until then, `socat unix-listen:/tmp/remote-docker.sock,fork tcp:<ip>:2375` is my friend.

**Comment by lispyclouds** [comment]
Would be addressed when https://github.com/into-docker/unixsocket-http is used as the lib.

**Comment by lispyclouds** [comment]
http:// supported now!
