### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Sardtok** [into-docker/clj-docker-client#34]
#30 might fix this, but the current use of unixsocket-http means there's no HTTPS, as it only supports HTTP, TCP and UNIX sockets. The clj-docker-client README references use of HTTPS. Unless HTTPS support is added, the reference to using HTTPS should be removed.

**Comment by lispyclouds** [comment]
Good catch! this is a remenant of the older implementation and I'll remove the mention in the README. Additionally I'll try to open a patch upstream to see if this can be added. Thanks!
