### ISSUE TITLE
:NetworkCreate returns {:message "got EOF while reading request body"}

### ISSUE THREAD

**Issue by sergeiudris** [into-docker/clj-docker-client#40]
### problem

- cannot create a network (and could find network tests as a reference), always returns {:message "got EOF while reading request body"}

```clojure
(def networks (docker/client {:category    :networks
                              :conn        {:uri "unix:///var/run/docker.sock"}
                              :api-version "v1.41"}))

(docker/invoke networks
                     {:op     :NetworkCreate
                      :params {:body {:Name "foo"}}})
;; => {:message "got EOF while reading request body"}
```
### env

<details><summary>docker version</summary>
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

</details>

`deps.edn`:
```clojure
org.clojure/clojure {:mvn/version "1.10.3-rc1"}
github.into-docker/clj-docker-client {:git/url "https://github.com/into-docker/clj-docker-client"
                                              :sha "5d3f1a3568c24b9029eb193fd3ff5daf16f32bd2"
                                              :tag "1.0.2"}

```

**Comment by lispyclouds** [comment]
Hey @sergeiudris , thanks for posting this, using a `networkConfig` should make it work:
```clojure
(invoke networks
        {:op     :NetworkCreate
         :params {:networkConfig {:Name "foo"}}})
```
This is is buried deep in the docs here:
https://github.com/into-docker/clj-docker-client/blob/main/resources/clj_docker_client/api/v1.41.yaml#L9114

Apologies for the confusion caused as the API docs are pretty sketchy and I haven't gotten around to making a proper help setup for this 😕 Also running `doc` kinda hints this too:
```clojure
(doc networks :NetworkCreate) ; => {:doc Create a network :params ({:name networkConfig})}
```
Also the API is quite extensive to test it all out, a PR for this is most welcome or can add an example for it? Hope this helps? 😄

**Comment by sergeiudris** [comment]
> Hey @sergeiudris , thanks for posting this, using a `networkConfig` should make it work:
> 
> ```clojure
> (invoke networks
>         {:op     :NetworkCreate
>          :params {:networkConfig {:Name "foo"}}})
> ```
> 
> This is buried deep in the docs here:
> https://github.com/into-docker/clj-docker-client/blob/main/resources/clj_docker_client/api/v1.41.yaml#L9114
> 
> The issue here is that the docker daemon simply gives a 400 without any helpful message and hence you see the weird error.
> 
> Apologies for the confusion caused as the API docs are pretty sketchy and I haven't gotten around to making a proper help setup for this  Also running `doc` kinda hints this too:
> 
> ```clojure
> (doc networks :NetworkCreate) ; => {:doc Create a network :params ({:name networkConfig})}
> ```
> 
> Also the API is quite extensive to test it all out, a PR for this is most welcome or can add an example for it? Hope this helps?

works, thank you!

- link to docs is more than enough - so far I used https://docs.docker.com/engine/api/v1.41/#operation/NetworkCreate as main ref, now - thank you for pointing out - will pay attention and get used to understanding args from /resources files
- api is generated (which is awesome), so having few basic tests is totally logical - rest is analogous, and now I know to reference .yml files as the source-of-truth for args

**Comment by sergeiudris** [comment]
- alhtough not critical, still - i spent quite some time with this problem - so opened a PR https://github.com/into-docker/clj-docker-client/pull/41
- hope this small addtion to readme saves someone some time, creating a network is a useful operation
- take no credit, but super happy is works
