### ISSUE TITLE
docker build ?

### ISSUE THREAD

**Issue by behrica** [into-docker/clj-docker-client#43]
How to do a docker build with the API ?
 I assume, I need to create a tar file or similar and cannot use ".",
as on the docker cli.
Do you have an example for this ?

**Comment by lispyclouds** [comment]
Hey, so the API builds using the context passed as a TAR archive as mentioned in https://docs.docker.com/engine/api/v1.41/#operation/ImageBuild
For this you can try:
```clojure
(docker/invoke images {:op     :ImageBuild
                       :params {:inputStream <input stream of the dir as a TAR>}})
```
you need to TAR the dir upfront and pass it as a stream. can see the options here: https://github.com/into-docker/clj-docker-client/blob/main/resources/clj_docker_client/api/v1.41.yaml#L7211

hope this helps? 😄

**Comment by lispyclouds** [comment]
The tarring is done by the docker cli when you say `docker build .`
